/** Frontend keys must match API GET /settings response (see beancircle-api settings.constants.ts) */
export const SETTINGS_API_KEYS = [
  'lastSeenVisibility',
  'onlineStatusVisibility',
  'readReceipts',
  'profileVisibility',
  'socialLinksDefaultVisibility',
  'showLastSeen',
  'pushNotifications',
  'messageNotifications',
  'mentionNotifications',
  'groupNotifications',
  'marketingNotifications',
  'emailNotifications',
  'notificationSound',
  'notificationVibration',
  'accentColor',
  'fontSize',
  'messageDensity',
  'chatWallpaper',
  'autoDownloadMedia',
  'mediaQuality',
  'saveDrafts',
  'linkPreviews',
  'typingIndicators',
  'autoCleanupDays',
  'locationVisibility',
  'discoveryVisibility',
  'showOnlineStatus',
  'updatedAt',
] as const;
